# poc typique pour un déploiement automatisé Komodo
# sera déployé sur la vm komodo
name: blavogiez.fr

# domaine dynamique grace a traefik, spécifié par le conteneur
services:
  app:
    build: .
    container_name: blavogiez.fr
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kanboard.rule=Host(`apercu-site.blavogiez.fr`)"
      - "traefik.http.routers.kanboard.entrypoints=web"
      - "traefik.http.services.kanboard.loadbalancer.server.port=80"
    networks:
      - default
      - proxy
      # si cest pour test en dehors de komodo, on desactive ce reseau
      # - proxy
    # test uniquement, a desac pour komodo
    #ports:
    #  - 9090:80

networks:
  default:
  proxy:
    external: true